# Makefile generated by configure script

# Variables
CC = gcc
CFLAGS = -Wall -Wextra -pedantic -std=c99 
LDFLAGS = -lcurl 
TARGET = bin/csvToJSON
SRC = src/csvToJSON.c src/csvToJSON_lib.c
TEST_TARGET = bin/test_csvToJSON
TEST_SRC = src/test_csvToJSON.c src/csvToJSON_lib.c

# Default target
all: $(TARGET) $(TEST_TARGET)

# Build target
$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC) $(LDFLAGS)

# Build test target
$(TEST_TARGET): $(TEST_SRC)
	$(CC) $(CFLAGS) -o $(TEST_TARGET) $(TEST_SRC) $(LDFLAGS)

# Run tests
test: $(TEST_TARGET)
	./$(TEST_TARGET)

# Clean target
clean:
	rm -f $(TARGET) $(TEST_TARGET)

# Phony targets
.PHONY: all clean test
